python main.py --dataset exp1a --hid_units 2 --sc 0
python main.py --dataset exp1a --hid_units 3 --sc 0
python main.py --dataset exp1b --hid_units 2 --sc 0
python main.py --dataset exp1b --hid_units 3 --sc 0
python main.py --dataset exp1c --hid_units 2 --sc 0
python main.py --dataset exp1c --hid_units 3 --sc 0
python main.py --dataset exp1d --hid_units 2 --sc 0
python main.py --dataset exp1d --hid_units 3 --sc 0
python main.py --dataset exp2a --hid_units 2 --sc 0
python main.py --dataset exp2a --hid_units 3 --sc 0
python main.py --dataset exp2b --hid_units 2 --sc 0
python main.py --dataset exp2b --hid_units 3 --sc 0
python main.py --dataset exp2c --hid_units 2 --sc 0
python main.py --dataset exp2c --hid_units 3 --sc 0
python main.py --dataset exp3 --hid_units 2 --sc 0
python main.py --dataset exp3 --hid_units 3 --sc 0
python main.py --dataset exp4 --hid_units 2 --sc 0
python main.py --dataset exp4 --hid_units 3 --sc 0
python main.py --dataset exp5 --hid_units 2 --sc 0
python main.py --dataset exp5 --hid_units 3 --sc 0
python main.py --dataset exp6 --hid_units 2 --sc 0
python main.py --dataset exp6 --hid_units 3 --sc 0
python main.py --dataset exp7 --hid_units 2 --sc 0
python main.py --dataset exp7 --hid_units 3 --sc 0
python main.py --dataset exp8 --hid_units 2 --sc 0
python main.py --dataset exp8 --hid_units 3 --sc 0
python main.py --dataset exp9 --hid_units 2 --sc 0
python main.py --dataset exp9 --hid_units 3 --sc 0